version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: pomodoro-api
    restart: unless-stopped
    ports:
      - "53050:53050"